In [ ]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import joblib


: 

In [ ]:
class perceptron:
  def __init__(self, eta: float=None , epochs: int=None):
    self.weights = np.random.rand(3) * 1e-4 #small random weights
    training = (eta is not None) and (epochs is not None)

    if training:
      print(f"inital weight before training :: {self.weights}")
    self.eta = eta 
    self.epochs = epochs


  def _z_outcome(self, input, weights):
    return np.dot(input, weights)

  def activation_function(self,z):
    return np.where(z>0,1,0)

  def fit(self ,x,y):
    self.x = x
    self.y=y
    
    x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]
    print(f"x with bias : {x_with_bias}")

    for epoch in range (self.epochs):
      print("--"*10)
      print(f"for epoch >> {epoch}")
      print("--"*10)

      z = self._z_outcome(x_with_bias, self.weights)
      print(f"value of z :: {z}")

      y_hat = self.activation_function(z)
      print(f"predicted value after foreward passs:: {y_hat}")

      self.error = self.y - y_hat
      print(f"error :: {self.error}")

      self.weights = self.weights + self.eta * np.dot(x_with_bias.T,self.error)
      print(f"updated weights after epochs: {epoch}/{self.epochs} :: {self.weights}")
      print("##"*10)




  def predictoion(self,x):
    x_with_bias = np.c_[x,-np.ones((len(self.x),1))]
    z = self._z_outcome(x_with_bias)
    return self.activation_function(z)



  def total_loss(self):
    total_loss = np.sum(self.error)
    print(f"total loss :: {total_loss}")
    return total_loss

  def _create_dir_return_path(self,model_dir,filename):
    os.makedirs(model_dir,exist_ok = True)
    return os.path.join(model_dir,filename)

  def save(self,filename , model_dir=None):
    if model_dir is not None:
      model_file_path = self._create_dir_return_path(model_dir,filename)
      joblib.dump(self,model_file_path)
    else:
      model_file_path = self._create_dir_return_path("model",filename)
      joblib.dump(self,model_file_path)

  def load(self, filepath):
    return joblib.load(filepath)

In [ ]:
def prepare_dataset(df,target_column="y"):
  X = df.drop(target_column,axis=1)
  y = df[target_column]

  return X,y

In [ ]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
X,y = prepare_dataset(df_AND)

ETA = 0.1 
EPOCHS = 10

model_and = perceptron(eta=ETA, epochs=EPOCHS)
model_and.fit(X,y)

_ = model_and.total_loss()

inital weight before training :: [9.90601751e-05 4.71288477e-05 2.53877608e-05]
x with bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
value of z :: [-2.53877608e-05  2.17410868e-05  7.36724143e-05  1.20801262e-04]
predicted value after foreward passs:: [0 1 1 1]
error :: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epochs: 0/10 :: [-0.09990094 -0.09995287  0.20002539]
####################
--------------------
for epoch >> 1
--------------------
value of z :: [-0.20002539 -0.29997826 -0.29992633 -0.3998792 ]
predicted value after foreward passs:: [0 0 0 0]
error :: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epochs: 1/10 :: [9.90601751e-05 4.71288477e-05 1.00025388e-01]
####################
--------------------
for epoch >> 2
--------------------
value of z :: [-0.10002539 -0.09997826 -0.09992633 -0.0998792 ]
predicted value after foreward passs:: [0 0 0 0